---
title: "Final"
author: "Vincent Morin"
date: "12/2/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = F,error=F,comment = F)
require(tidyverse)
require(tidytext)
require(lubridate)
require(ggthemes)
require(textdata)
require(topicmodels)
require(recipes)
require(caret)
```


Import the dataset

```{r}

# Import Dataset
GreenData = read_csv("Data/2016_Green_Taxi_Data.csv") 

```


Calculate time per trip in seconds, add as new variable. 

```{r}
GreenData <- GreenData %>% mutate(
  Trip_Duration = 
    Lpep_dropoff_datetime-lpep_pickup_datetime)



GreenData %>% glimpse()
```


Add new variables

```{r}

GreenData$Pickup_hour <- 
  hour(GreenData$lpep_pickup_datetime)




GreenData$Pickup_day <- 
  day(GreenData$lpep_pickup_datetime)




GreenData$Pickup_week <-
  hour(GreenData$lpep_pickup_datetime)




GreenData %>% glimpse()
```

Add a variable for average speed per trip. 

```{r}
GreenData <- hm(GreenData$Trip_Duration)

#GreenData <- GreenData %>% mutate(
  #Trip_speed = Trip_distance/Trip_hours
#)

GreenData %>% glimpse()
```
